services:
  - type: worker
    name: stock-market-bot
    runtime: python
    plan: free
    pythonVersion: "3.11.10"
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    autoDeploy: true
